repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
      language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    - id: isort
      language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: master
    hooks:
    - id: eslint

  - repo: git://github.com/elidupuis/mirrors-sass-lint
    sha: master
    hooks:
    - id: sass-lint
