version: '3.2'

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://bbp:bbp@postgres:5432/bbp
      MEDIA_ROOT: /var/media
      PYTHONDONTWRITEBYTECODE: 1
      REDIS_URL: redis://redis:6379
      SECRET_KEY: notverysecret
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: media
        target: /var/media

  postgres:
    image: "postgres:alpine"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=bbp
      - POSTGRES_PASSWORD=bbp
      - POSTGRES_USER=bbp
    logging:
      driver: "none"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata

  redis:
    image: "redis:alpine"
    logging:
      driver: "none"

volumes:
  media:
  pgdata:
