version: '3.2'

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://bbp:bbp@postgres:5432/bbp
      - DJANGO_SETTINGS_MODULE=bbp.settings.dev
      - PYTHONDONTWRITEBYTECODE=1
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=notverysecret
    expose:
      - 8000
    volumes:
      - type: bind
        source: .
        target: /app

  frontend:
    command: "npm run start"
    image: "node:12"
    ports:
      - "3000:3000"
    user: node
    volumes:
      - type: bind
        source: .
        target: /home/node/app
    working_dir: /home/node/app

  postgres:
    image: "postgres:alpine"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=bbp
      - POSTGRES_PASSWORD=bbp
      - POSTGRES_USER=bbp
    logging:
      driver: "none"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata

  redis:
    image: "redis:alpine"
    logging:
      driver: "none"

volumes:
  pgdata:
