version: '3.2'

services:
  web:
    volumes:
      - type: bind
        source: .
        target: /app

  frontend:
    command: "npm run start"
    image: "node:12"
    ports:
      - "3000:3000"
    user: node
    volumes:
      - type: bind
        source: .
        target: /home/node/app
    working_dir: /home/node/app
