version: '3.2'

services:
  web:
    build:
      args:
        POETRY_ARGS: ""
    command: ./manage.py runserver 0:8000
    environment:
      DJANGO_SETTINGS_MODULE: bbp.settings.dev
      PYTHONBREAKPOINT: pudb.set_trace
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app

  frontend:
    command: "npm run start"
    image: "node:12"
    ports:
      - "3000:3000"
    user: node
    volumes:
      - type: bind
        source: .
        target: /home/node/app
    working_dir: /home/node/app
