# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
            DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - cache-{{ checksum "Pipfile.lock" }}
          - cache-

      - run:
          name: install dependencies
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      - run:
          name: run tests
          command: |
            pipenv shell
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
