# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install linters 
          command: |
            pipenv install --skip-lock flake8 isort

      - run:
          name: flake8
          command: pipenv run flake8

      - run:
          name: isort
          command: pipenv run isort --check-only

      - setup_remote_docker

      - run:
          name: Build image 
          command: docker-compose build

      - run:
          name: Check for missing migrations
          command: |
            docker-compose run --rm web ./manage.py makemigrations --check

      - run:
          name: Run tests
          command: |
             docker-compose run --rm web ./manage.py test

#   deploy:
#     docker:
#       - image: docker:latest

#     steps:
#       - checkout

#       - run:
#           name: Deploy to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


# workflows:
#   version: 2

#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
