# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install dependencies
          command: |
            poetry install -n

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: black
          command: poetry run black --check .

      - run:
          name: flake8
          command: poetry run flake8

      - run:
          name: isort
          command: poetry run isort --check-only

      - setup_remote_docker

      - run:
          name: Build image
          command: docker-compose build

      - run:
          name: Django system checks
          command: |
            docker-compose run --rm web ./manage.py check --deploy

      - run:
          name: Check for missing migrations
          command: |
            docker-compose run --rm web ./manage.py makemigrations --check

      - run:
          name: Run tests
          command: |
             docker-compose run --rm web ./manage.py test
