# Generated by Django 2.0.8 on 2018-09-11 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('pages', '0002_auto_20180911_0648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BBPPage',
            new_name='BasicPage',
        ),
    ]
